### PR TITLE
Hotline + animal updates

### PR DESCRIPTION
**Pull request by AlexMountain**
Updates to the hotline and Animal sections with sidebar and theme changes.

### CODE REVIEW

**Comment by trevorskaggs** [comment]
image
Not really sure this is bug, but on a big monitor, the buttons and frame expand to fill the whole space, but fields do not.

image
Looks like we missed the "Edit Reporter" button.  Not sure if that was intentional?
 
image
This image is from when "Editing Owner", might need conditional button verbiage?

image
This "Edit Service Request" button isnt hooked in, I dont think!


image
image
When I click on the "Edit Owner" from the Service Request Details page and there is a Reporter present, it seems to populate with the data from the Reporter!

**Comment by trevorskaggs** [comment]
Ready for review on July 23

**Comment by AlexMountain** [comment]
@trevorskaggs I'd like to take another round at our details pages but we can do that in a later ticket.  I think I got the bug fixes in except the button placement since we'll be changing those down the line more anyways so please take it for another review when you get a chance!

**Comment by trevorskaggs** [comment]
Will review this afternoon!

**Comment by trevorskaggs** [comment]
Changes are looking good! Still had a bit of struggle with the prod server components, but ultimately I test against master with 3 commits CP'd on top:

**Comment by trevorskaggs** [comment]
Was able to circle back and get my environment fixed up.  This ticket has been test on the end of the actual branch. :shipit:

**Pull request merged**
