### PR TITLE
populates missing animal data on owner summary

### LINKED ISSUE #446: Owner Summary Animal Fields Not Populating
image
image

### PR DESCRIPTION
**Pull request by parksjr**
(closes #446)

### CODE REVIEW

**Comment by trevorskaggs** [comment]
Looking good, a few non bug related notes if we can squash them here:
image
- Can we get Primary/Secondary Color on the same lines?
- Anyway to page break if an animal is going to overlap a page? See above for an example!

**Comment by trevorskaggs** [comment]
@parksjr yea i did mean to merge it so that I could test it without losing my ability to also test that ticket quickly!  The Incident ticket will be merged soon, so im good with either reverting or leaving it.  Yea, lets split the page break out if that is easier for you.

**Comment by parksjr** [comment]
> @parksjr yea i did mean to merge it so that I could test it without losing my ability to also test that ticket quickly! The Incident ticket will be merged soon, so im good with either reverting or leaving it. Yea, lets split the page break out if that is easier for you.

Cool, just making sure you didnt mean to ship it to prod or something. if its easier for you its all good, shouldnt have issues just as long as you mean to push the incident branch to prod before this one.

**Comment by parksjr** [comment]
I've updated this branch on top of the latest master branch (after incident merged)

**Pull request merged**
