### PR TITLE
Add SR map to Hotline page.

### PR DESCRIPTION
**Pull request by AlexMountain**
- [x] Add map to Hotline page
- [x] Filter based on status
- [x] Colorize dots based on status (Open: Green, Assigned: Yellow, Closed: Red)
- [x] Access to SR details

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs Ready for review!

**Review by trevorskaggs — COMMENTED** [review]
God damn this is sexy! I really like this functionality! The open SRs in a new tab is 💯 .

Only issue that I really found was when a SR is closed the tooltip seems to be a bit wonky because there are no animals in the SR still:
image


Also: zooming to extent when changing filters is 🔥 🔥 🔥 🔥 🔥

**Comment by AlexMountain** [comment]
@trevorskaggs Great catch!  Ready once again.

**Review by trevorskaggs — APPROVED** [review]
Cash Money. :shipit:

**Pull request merged**
