### PR TITLE
Shelter drag and drop improvements.

### PR DESCRIPTION
**Pull request by AlexMountain**
- [x] Highlight dragging object and droppable locations when active
- [x] Filter available rooms by building selection
- [x] Give rooms a fixed height and make scrollable
- [x] Handle long animal names

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs Ready for review!

**Review by trevorskaggs — COMMENTED** [review]
image
image
- Not sure if its related to this ticket, but I seem to be missing an animal?
- When we click the "Assign Animals" button from the Building/Room context, how hard would it be to start with that context on the Assign page? Basically auto-switching to the current Building?
- When there are no rooms associated to a given building, can we display a "No Rooms" type thing?
image

**Comment by AlexMountain** [comment]
@trevorskaggs Ready for rereview!  I made an attempt to fix the missing animal bug but not sure since I couldn't reproduce.  If you're still seeing that ping me so we can track it down.

**Review by trevorskaggs — APPROVED** [review]
Full Send! 🚜 🦝

**Pull request merged**
