### PR TITLE
Use FontAwesome Pro icons

### PR DESCRIPTION
**Pull request by AlexMountain**
- [x] Use FA Pro icons
 - [x] Add a tooltip to every icon
 - [x] Update dispatch map tooltip icons

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs The functionality for this one should be ready for review!

requires:
```
npm config set "@fortawesome:registry" https://npm.fontawesome.com/
npm config set "//npm.fontawesome.com/:_authToken" TOKEN
npm install @fortawesome/pro-solid-svg-icons
```

**Comment by rmeyers4** [comment]
@AlexMountain : Tests are now passing! I was missing `house-circle.png` so I just changed the file to see if tests would pass in this commit: https://github.com/trevorskaggs/shelterly/pull/209/commits/ea2719947317d98d4f8ad60f83f1374e4a23c773
Once you add that file to this pull request you can revert that commit

**Comment by AlexMountain** [comment]
Thanks @rmeyers4 !!

**Comment by trevorskaggs** [comment]
Icon seem to be populated and looking good!  Not sure if its specifically from this ticket, but opening the SR details page yields the following error: `Error: React.Children.only expected to receive a single React element child.`
image
After that I seem to get logged out!

**Comment by trevorskaggs** [comment]
Nevermind, figured out it was related to a merge resolution issue! Should be fixed and really like the tooltips!  Also added a tool tip to the new cancel SR button. Lets ship this bad boy!

**Review by trevorskaggs — APPROVED** [review]
Full Send! 🚢 🇮🇹

**Pull request merged**
