### PR TITLE
add back button to personform

### LINKED ISSUE #64: Add back button
Move the back button from card footers to the header.

### PR DESCRIPTION
**Pull request by rmeyers4**
Closes #64

### CODE REVIEW

**Comment by rmeyers4** [comment]
@trevorskaggs : ready for review.

**Comment by trevorskaggs** [comment]
Looking good!

image

It seems to take you back to the Hotline Landing Page when clicked.  If you are deeper into a workflow, is that still the intention? Do we want to figure out how to actually "go back a page" in the workflow? For instance when going Non-Owner and selecting "Add Owner", if on the Owner page you click the Back button, it took me back to the Hotline Landing.

**Comment by AlexMountain** [comment]
@trevorskaggs Pretty sure it's just working the way it was before.  I think that is actually a pretty complex problem.  At first I thought it would just be a matter of implementing https://github.com/trevorskaggs/shelterly/issues/61, but I think it's even more than that.  Say the back button on the Owner page takes you to the Reporter, now what?  Is it a blank Reporter form?  or are we loading the previously created reporter data in?  If loading, now do we no longer want to be saving another new reporter, but instead just updating before moving onto Owner?  

Seems it will require some work probably best done in another ticket if we want it to do the above.

**Comment by trevorskaggs** [comment]
Agreed.  This is good to go then!

**Pull request merged**
