### PR TITLE
UI requests

### PR DESCRIPTION
**Pull request by AlexMountain**

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs Ready for review!

**Comment by trevorskaggs** [comment]
Looking good!
#354 ✔️ 
#371 ✔️ 
#372 ✔️ 
#370 (see notes below)
#369 ✔️  and 💯 !
#353 ✔️ 
#361 ✔️ 

Found a few little issues:
1. When attempting to save a DAR, it looks like the frontend is still trying to require the Owner and Owner Contact Time fields: 
image
2. When selecting a Owner/Contact Time I get this on the backend: 
image

**Comment by AlexMountain** [comment]
@trevorskaggs Oops, had some code not committed on that one - should be ready again!

**Comment by trevorskaggs** [comment]
Awesome, thanks for the update! That works like expected.  After playing with it, lets do the "not required" for the contact note field also as I think they ultimately want to be able to skip that whole section and they missed that field explicitly in the requirement.  After that, let's merge this guy up and I will roll a release for them to see all the cool new things!

**Pull request merged**
