### PR TITLE
Adds print all buttons to all searchable pages

### LINKED ISSUE #508: Add ability to download as PDF all Search Pages

### LINKED ISSUE #513: Compress PDFs
The minimal PDF size is currently coming down as 10.3 MB

### LINKED ISSUE #516: Modify Animal Care Schedule
- [ ] Add Shelter Location
- [ ] Remove Owner Phone Number
- [ ] Make Date Time and AR# Columns Smaller

### PR DESCRIPTION
**Pull request by parksjr**
This PR adresses 3 issues (#508, #513, #516), below are notes on each.

## Issue #508 - print all button on all search pages
As advertised, the "Print All" button exists on all the search pages now

## Issue #513 - pdf file sizes
This was a simple change available via the core pdf library we are using, and file sizes are <1mb instead of 10mb, thats awesome! However, a noticeable lag now exists between user click and file download, and given the nature of the change, that is to be expected. I added a "spinner" to those buttons to help UX.

Note: I wanted to add the spinner to the original print icon buttons (on the details pages) but that change wasn't easy and started to blow up scope. A nice to have ticket should be filed.

## Issue #516 animal care schedule
This is all good, one thing though, I was not 100% sure how to show the shelter location, so if a shelter object exists, I display the location info, including address, building and room name if available, and on a new line below the main image part. Let me know if that's what was desired.

More notes:

ShelterlyPDF updates
 - smaller file size on save
 - customizable column sizes for animal care schedule
 - fixes paging in the middle of "components"
 - fast image compression (to aid file size)
 - returns Promise on saveFile

closes #508
closes #513
closes #516

### CODE REVIEW

**Comment by trevorskaggs** [comment]
Awesome @parksjr!  For the Shelter Location, lets just do this format if they are sheltered: `Shelter Name / Building Name / Room Name`

**Comment by trevorskaggs** [comment]
Also, noticed there are Page Numbers on DA/SR Download All, but the numbers are for the larger packet.  Currently for single downloads those page numbers are just for the given SR/DA.

**Comment by parksjr** [comment]
@trevorskaggs - I fixed up the shelter name on the animal schedule, and I added the page numbers to owner(s). The page numbers on the print all will take a little extra effort, i'd say if you can live with it as is we can put a nice-to-have ticket in for that so it doesn't have to hold up merging this in.

**Comment by trevorskaggs** [comment]
Thanks dude!  On the second spin I only found a few weird things!
1. It seems like the Owner Search page now throws a couple warnings, that dont effect functionality, but if they are easy to fix!:
image
image

**Comment by parksjr** [comment]
@trevorskaggs fixed the above dom warnings

**Review by trevorskaggs — APPROVED** [review]
Last round of changes look good! :shipit:

**Pull request merged**
