### PR TITLE
Make details links from searches open in a new tab.

### PR DESCRIPTION
**Pull request by AlexMountain**
- [x] Make all clipboard details links in search results open in a new tab.
- [x] Make a pass on all search pages for consistency.
- [x] Fix hotline SR creation with only a reporter.
- [x] Allow DA search to find results based on animal names.

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs Ready for review!

**Review by trevorskaggs — APPROVED** [review]
Send it!

**Review by trevorskaggs — APPROVED** [review]
Rereview looking good, :shipit:

**Comment by trevorskaggs** [comment]
image

**Comment by AlexMountain** [comment]
I see it's working!  haha

**Pull request merged**
