### PR TITLE
Continued Map Enhancements

### PR DESCRIPTION
**Pull request by AlexMountain**
- [x] Need to make Map respect "Follow Up Date" constraint.
 - [x] Add ability to disregard "Follow Up Date" when needed. Add toggle next to ACO Required > "Pending Only" that will show/hide those that are currently before Follow Up Date.
 - [x] Lock Map to always be full viewable.

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs This is ready for review!

**Comment by trevorskaggs** [comment]
Looking sharp!

- [ ] Map is staying fixed, but the stuff at the bottom seems to be able to scroll under.  Maybe we need to make the SR table its own container/scrollable?
image

**Comment by AlexMountain** [comment]
@trevorskaggs I changed strategies from the sticky map to just making the SR list scrollable.  Definitely feels better.  Moved some other things around, let me know if you approve!

**Review by trevorskaggs — APPROVED** [review]
looks good!

**Pull request merged**
