### PR TITLE
adds printable intake summary on click to owner details #404

### LINKED ISSUE #404: Intake Summary Printout
Objective of this would be to print a summary of the Owner Detail page.  The intention of this would be to have the ability to hand out the information directly to the owner after Intake.

image

Top would be the "Information" Section about the owner, then we would want to list out the animals attached to the owner.
For each animal, let's output the following: ID, Name, Species, Sex, Primary, Secondary Color, Breed/Description, Shelter Address.

### PR DESCRIPTION
**Pull request by parksjr**
Added the button to download a printable intake summary from the owner details screen, see attached pdf of an example of what that looks like (from my local environment). Let me know of any changes and i'll work it in.

[Intake-Summary-022 (32).pdf](https://github.com/trevorskaggs/shelterly/files/8748272/Intake-Summary-022.32.pdf)

Additionally, I've included the shelter_object to the ModestAnimalSerializer class, which  will have performance implications. The measure of those implications I don't know, but it's worth taking a gander at some point I'm sure instead of continuing to include fields like this down the road. At what point would it be a better remeasure to create a new serializer, or optional include?

Closes #404

### CODE REVIEW

**Comment by trevorskaggs** [comment]
@AlexMountain Any opinion on the performance implications highlighted above?

**Comment by trevorskaggs** [comment]
Coming along nicely! Now that I see it in person a few modifications (sorry):

image
1. Space between Service and Request in the Owner Details Section
2. Can we add a HR below `Owner Detail` to make that section have the same spacing/feel as the Animals section?
3. Let's add `Status` to the Animal Details section for each animal.
4. Can we Capitalize the species?
5. Last one: I realize that this is more of a Owner Summary now instead of a Intake Summary as this is going to be valuable for evacuated animals also when their owners arrive.  Can we rebrand that in the couple of locations: Tooltip on button, top of the report, filename?

**Comment by parksjr** [comment]
latest commit addresses modifications, let me know how it looks.

**Comment by trevorskaggs** [comment]
Thanks for the update, last little nitpicky things:
1. Can we add a space between Service and Request in the Owner Details section?
2. Standardize Case on Status Field (SHELTERED IN PLACE vs Sheltered In Place)
3. Can we fix the icon spacing at the top? Looks a little wide?
image

**Comment by AlexMountain** [comment]
If we have performance problems I don't think it will be because of this. Probably easier to use as is for now and address as a part of a larger performance effort if we feel it's ever warranted.

**Comment by parksjr** [comment]
@trevorskaggs , I fixed those last three things, I understood what you meant about a space between Service and Request this time 😆

**Review by trevorskaggs — APPROVED** [review]
Looking awesome, thanks for the changes!

**Pull request merged**
