### PR TITLE
Track and filter teams by incident.

### PR DESCRIPTION
**Pull request by AlexMountain**

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs Finally ready for review! Requires a migration.

**Review by parksjr — COMMENTED** [review]
Is this what fixed build/test issues?

**Comment by AlexMountain** [comment]
Removing `drf_yasg` cleared it up.

**Comment by trevorskaggs** [comment]
Everything checks out except the main issue!  I'm still seeing active teams from different Incidents!

image
image

**Comment by AlexMountain** [comment]
@trevorskaggs Fixed! Did you want to retest?

**Pull request merged**
