### PR TITLE
Issues/218 dar pdf download

### PR DESCRIPTION
**Pull request by trevorskaggs**

### CODE REVIEW

**Comment by trevorskaggs** [comment]
@parksjr Can we move the "Print Button" next to the clipboard on this page?
image

**Comment by parksjr** [comment]
Added the print icon/button for the offline resolution form to the Summary page (aslo fixed a bug with the animal grid on said pdf). I kept the button to download from the form as well, I figured why not have it in both places, but if you think it should only be on the Summary i can get rid of it on the online form, let me know either way.

**Comment by trevorskaggs** [comment]
Client Updates:
- Make first page a summary page.  Need to include the following:
- SR: ID, Address, Animal Counts (2 Dogs, 1 Cat, etc.)
- Hard Page Break to cause the first SR to be on its own page

- For the Animal section would need to make a few updates/additions.
- Would we be able to maybe push this into a Table?  Something like this:
Animal ID | Animal Name | Species | SIP | UTL | Sheltered | Deceased
A#1           | Jeff                 | Cat        |  [ ]  |   [ ]  |      [X]       |         [ ] 
Primary Color:   Black, Secondary Color: White
Description: Has snowshoe markings.  Will typically be found under the back deck.
Behavior: Slightly human averse, can be coaxed with treats.
A#2           | Steve              | Dog       |  [X] |   [ ]  |     [ ]        |         [ ] 
Primary Color:   Tan, Secondary Color: Brown
Description: Looks like a German Shepard, very friendly
Behavior: N/A

- Priority Section:
- Can we make these checkboxes horizontal (maybe shrink font size)?
- Can we put a `(Current)` next to the level the SR currently is?

-Dates:
Can we put a format like "__ / __ / ____ (Month/Day/Year)" to help people on these fields?

Notes Fields
- They want to see at least 4 lines for to allow for longer notes.  That being said, the line spacing can be reduced to compact everything a bit more.

**Comment by parksjr** [comment]
@trevorskaggs I just pushed up some changes that covers just about everything requested above. Only one thing remains, the Behavior Notes are not present in the animal object, so it is always N/A right now. I am not sure what the fix should be right now. Other than that everything should be as requested. 

closes #218

**Comment by trevorskaggs** [comment]
Thanks for the update @parksjr ! I pulled down the most recent changes and straight away am getting: 
image
This is true for existing and newly created DAs!

**Comment by trevorskaggs** [comment]
Also thought of another change that I didnt list before: can we have the file name be `DAR-###.pdf`?

**Comment by parksjr** [comment]
@trevorskaggs sorry for the delay. couple updates here:

- was able to reproduce as you did, and fixed the bug
- pdf file name changed
- added the behavior_notes to the SimplAnimalSerializer as @AlexMountain suggested on standup
- rebased the branch to resolve conflicts
- easy peasy 😄 

if you see anything else let me know and Im on it

**Comment by trevorskaggs** [comment]
@parksjr Thanks for the update duuuude!   Looking super clean.

Couple small things:
1. 
image
Looks like maybe we may need wrapping on Behavior (and maybe description field)?
2. I think I was not 100% clear on the Summary Page! I like the look, but I was thinking all the Summaries would be on the "Cover Page". Basically, can we take the details from pages 1 and 4 and drop them both on page 1?  See Attached DAR-007.pdf
[DAR-007.pdf](https://github.com/trevorskaggs/shelterly/files/8542812/DAR-007.pdf)
3. On the Summary Page, can we also add a team section at the very top? Basically just something like this:
Team Name: Team 2
Members: Trevor Skaggs (530) 232-2323, Mike Parks (215) 555-5523

Thanks dude!

**Comment by trevorskaggs** [comment]
@parksjr THANKS DUDE! One last little tweak and then we will ship this guy! Can I get a line of space between the SRs on the summary page?
image

This is going to work awesome to get us out there with this functionality! Merge after the above change!!!!! :shipit:

**Comment by parksjr** [comment]
And i just figured out how to deploy a team to multiple SRs. Thanks for testing this so well. I just pushed that last change up, I'll merge when all the checks pass.

**Pull request merged**
