### PR TITLE
Reactify shelter management

### PR DESCRIPTION
**Pull request by trevorskaggs**

### CODE REVIEW

**Comment by SpencerjCarroll** [comment]
Current Task List:
[] Merge to master (after side-bar + UI changes) and resolve conflicts
[] Change shelter list layout to more of a "tile" layout similar to hotline
[] House building/room hierarchy to be housing within tile layout
[] Add `possible/current` capacity for shelter/building/room

**Comment by SpencerjCarroll** [comment]
This one should be ready for review.

**Comment by trevorskaggs** [comment]
Took a quick spin of this and I cant get paste the "Save" button on "Add Shelter".... Thoughts?

**Comment by AlexMountain** [comment]
@trevorskaggs What's the error?  Check either django logs or browser console, it should be there.  I suspect a possible database migration issue, but without the error we're just guessing.

**Comment by trevorskaggs** [comment]
Yea, didnt see anything in the browser console or the django logs:
image
image
It's like its not submitting?

**Comment by AlexMountain** [comment]
Gotcha, thanks!  That's still good info.  In my experience this behavior is usually a Formik Yup validation issue.  I'll let @SpencerjCarroll take a stab.

**Comment by trevorskaggs** [comment]
Yea, good call, I did those things, but will be helpful to record. Also thats what it was when I saw similar kind of the behavior before!

**Comment by trevorskaggs** [comment]
Pushed a couple of small things:
- Remove shelter relationship from Room object, we can infer i think and is a bit simplier
- Cleanedup all the old `localhost` style urls

Last thing that I found so far:
image
Looks like the building list is not populating on the shelter detail page!  Also if you look in the console I see double sets of requests from this page:
image
A set of them is requesting undefined!

**Review by AlexMountain — APPROVED** [review]
@SpencerjCarroll I made a few cleanup changes but this is lookin great!  Feel free to hit me up if you have any questions.  If you approve of the changes this is good to go!  🧙

**Comment by trevorskaggs** [comment]
Alright, this ticket is shaping up!  Couple of notes:
 - Can we add front end form validation?  When you dont enter a value for a required field it just kind of sits there!
 - What is our plans with the bottom buttons on the pages? 
image
 - Also I pushed up some style changes and a couple of bug fixes, check them out and let me know what you think!

**Comment by AlexMountain** [comment]
@trevorskaggs Added Yup form validation.  Left the buttons alone for now, I suggest we clean them up on another UI pass ticket.

**Comment by SpencerjCarroll** [comment]
Thanks for the review @AlexMountain the clean up changes look great! I am happy to do a another pass in a seperate ticket to polish off those UI tickets @trevorskaggs.

**Comment by trevorskaggs** [comment]
Sounds good to me! Send it! 🇸🇳 🇮🇹

**Pull request merged**
