### PR TITLE
Dispatch Summary Minimap

### PR DESCRIPTION
**Pull request by AlexMountain**
- [x] Add ability to add/remove team members from a dispatch assignment
- [x] Add a minimap to the dispatch summary page

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs Ready for review!

**Review by trevorskaggs — COMMENTED** [review]
I really like this change! This gives a fantastic context for the DA!
image
Only thing I see is a bit of extra space (depending on number of Team Members), can we maybe summarize the total counts for the entire DA in that space? # of Dogs, # of Cats, # of Horses, etc.?

**Comment by trevorskaggs** [comment]
Also, while we are here, can we put the address on the top line instead of the work "Service Request" for each card?
image

**Comment by AlexMountain** [comment]
@trevorskaggs I made the address change but I'm hesitant to quickly add more data to a space that can fill up dynamically without spending more time on it.  I'm thinking we're going to want another pass on polishing up the data displayed on this page so let's target it there.

**Pull request merged**
