### PR TITLE
Add Reported (SIP) status.

### PR DESCRIPTION
**Pull request by AlexMountain**

### CODE REVIEW

**Comment by trevorskaggs** [comment]
- [x] https://github.com/trevorskaggs/shelterly/issues/588
- [x] https://github.com/trevorskaggs/shelterly/issues/582
- [x] https://github.com/trevorskaggs/shelterly/issues/579

**Comment by trevorskaggs** [comment]
Minor change request: when an animal is no longer in the `Reported` status, can we show the `Status` column instead of the `Requested Service` column on the Animal Edit page?
image
image

**Comment by AlexMountain** [comment]
@trevorskaggs To what end? Changing the status here without going through a workflow would break things.

**Comment by trevorskaggs** [comment]
The field is locked, but provides more value after the Reported phase.

**Comment by trevorskaggs** [comment]
Closing as OBE

**Review by trevorskaggs — APPROVED** [review]
:shipit:

**Pull request merged**
