### PR TITLE
Handle duplicate assigned SRs when deploying.

### PR DESCRIPTION
**Pull request by AlexMountain**
- [x] Reject Deployment if 1 or more SRs are already assigned.
- [x] Allow for user to reselect with duplicate offenders removed.
- [x] Allow for user to continue on with duplicate offenders removed.
- [x] Grab all SRs on initial load and use front end filtering for ACO and Pending options.

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs Ready for review!

**Comment by trevorskaggs** [comment]
Pop-up prompt came up in the right scenario, but I think maybe the SR details are missing from the modal?
image
Otherwise, looking awesome!

**Comment by trevorskaggs** [comment]
Also ran into another small issue!  When selecting "Continue Without Duplicates", if all the SRs would be duplicates, you get the following error:
image
While this should not happen in most cases, if there is exactly 1 SR this could be a concern!

**Comment by AlexMountain** [comment]
@trevorskaggs Not sure how I messed up the SR list.  Good catch on the empty submission. Ready for rereview!

**Pull request merged**
