### PR TITLE
Intake walkin workflow

### PR DESCRIPTION
**Pull request by AlexMountain**
see https://github.com/trevorskaggs/shelterly/issues/36 for details

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs Should be ready for review!

**Comment by trevorskaggs** [comment]
Looking good so far! Found a few little things:
 - At the end, we are redirected to a page that doesn't exists (Intake Summary), but this is fine per our discussion!
- Not specifically an Intake issue, but when submitting a Horse I got the following errors:
image
image
Might be a few other validation issue around the new horse information?

**Comment by AlexMountain** [comment]
@trevorskaggs Yep, totally forgot about the backend validators when implementing Horse + Other.  Also the Intake Summary page is blank but does exist, however, the url had a bad trailing slash.  Should be ready for rereview.

**Comment by AlexMountain** [comment]
@trevorskaggs Were you planning on rereviewing this one?

**Comment by trevorskaggs** [comment]
Yup, that's on deck for my lunch break!

**Comment by trevorskaggs** [comment]
Both fixes are 💯 . Ship it!

**Pull request merged**
