### PR TITLE
Vet edit medical plan

### PR DESCRIPTION
**Pull request by AlexMountain**

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs This ended up being a bundled of minor feature requests and bug fixes. Should all be linked and ready for review.

**Comment by trevorskaggs** [comment]
Reviews:
- [ ] https://github.com/trevorskaggs/shelterly/issues/837
- [ ] https://github.com/trevorskaggs/shelterly/issues/826
- [ ] https://github.com/trevorskaggs/shelterly/issues/818
- [ ] https://github.com/trevorskaggs/shelterly/issues/785
- [ ] https://github.com/trevorskaggs/shelterly/issues/679
- [ ] https://github.com/trevorskaggs/shelterly/issues/849
- [ ] https://github.com/trevorskaggs/shelterly/issues/851
- [ ] https://github.com/trevorskaggs/shelterly/issues/862

**Comment by trevorskaggs** [comment]
- https://github.com/trevorskaggs/shelterly/issues/818: Looks like the MR link doesnt work from the VR Patient card. Pointing to url with `undefined` training2/vet/medrecord/undefined
- https://github.com/trevorskaggs/shelterly/issues/785: Im seeing a redirect to login page when hitting any of the routes in a "closed incident", but can we redirect to the incident selection page instead? Also, it looks like the redirect doesnt apply to the incident home route?
- https://github.com/trevorskaggs/shelterly/issues/849: For this one, I figured out how to edit, but with the new Medical Notes edit button, we have 2 different approaches to "editing" on that page, so might be confusing.
image

**Review by trevorskaggs — APPROVED** [review]
Looks good!

**Pull request merged**
