### PR TITLE
Issues/456 multiple animal care schedules

### LINKED ISSUE #455: Convert Animal Care Schedule to PDF
Currently the Animal Care Schedule is a hacked together django url with a template rendering.  Lets convert this to our new PDF approach.  The current structure/fields are roughly correct.
[AnimalCareSchedule.pdf](https://github.com/trevorskaggs/shelterly/files/9122974/AnimalCareSchedule.pdf)

Nice to Haves:
- [ ] QR Code in upper right corner to Animal Details page

### LINKED ISSUE #456: Allow Printing of Multple Animal Care Schedules as Single PDF
From the Animal Cards section, allowing for printing of all Animal Care Schedules

### PR DESCRIPTION
**Pull request by parksjr**
See #471 PR for the original commit, which had a bug reported on it. That might be fixed, need to confirm. On top of all of that this PR includes downloading multiple animal care schedules at once from the animals search page.

closes #455 
closes #456

### CODE REVIEW

**Comment by parksjr** [comment]
@trevorskaggs, the latest update includes print all animals button for Room, SR, and Owner details pages. Ready for review!

**Comment by trevorskaggs** [comment]
@parksjr This is awesome! Thank you!  Only suggestions I have are for file naming conventions. Can we include the Owner ID, Room ID, etc. and current date to the filenames? Getting a few duplicates quickly for the multi print!
image

**Comment by trevorskaggs** [comment]
Everything is look good so far! Just one weird thing, the Shelterly logo gets a little wonky on any page after the first one:
Page 1:
image
Page 2:
image

**Comment by parksjr** [comment]
Everything from Alex's notes should be all good with my latest push. One thing, though, item number 6, the phone number line on the PDF was already using the owner.display_phone prop which is the friendly formatted phone number field. I did a quick look for that on the backend and see it's a regex defined separately for each serializer. Without looking into how that function exactly works, I am assuming that if one or more of the capturing groups aren't satisfied, it falls back to the plain string?

**Pull request merged**
