### PR TITLE
Add new team member functionality to dispatch map.

### PR DESCRIPTION
**Pull request by AlexMountain**

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs Ready for review!

**Review by trevorskaggs — COMMENTED** [review]
1. If I only use New Team Members, I can seem to deploy the Team. Example being adding a single new member and selecting at least on SR.
image
2. If I add a New Member, then select an Existing Member, I get this error:
value.id is not iterable
TypeError: value.id is not iterable
    at http://localhost:3000/static/js/bundle.js:19700:39
    at Array.forEach (<anonymous>)
    at handleChange (http://localhost:3000/static/js/bundle.js:19699:12)
    at Object.onChange (http://localhost:3000/static/js/bundle.js:20959:33)
    at Typeahead._handleChange (http://localhost:3000/static/js/bundle.js:171203:43)
    at Typeahead.<anonymous> (http://localhost:3000/static/js/bundle.js:171342:22)
    at callCallback (http://localhost:3000/static/js/bundle.js:195688:16)
    at commitUpdateQueue (http://localhost:3000/static/js/bundle.js:195706:13)
    at commitLifeCycles (http://localhost:3000/static/js/bundle.js:201923:15)
    at commitLayoutEffects (http://localhost:3000/static/js/bundle.js:204435:11)

**Comment by AlexMountain** [comment]
@trevorskaggs Ready for rereview!

**Comment by trevorskaggs** [comment]
Seeing a few weird anomalies in here!
1. Still getting the phone number cleared out when adding an existing user to a new organization. In this example Bleh Smith was a member of ACCORN originally, and I added them to the new `Org` organization and it cleared out his phone number.
image
2.  The Dispatch Map hide behavior default is backwards in my head! When I land on this page, I want to default see all of the SRs that I should be currently dispatching.  In this branch I now have the count correct for how many are "pending", but it starts with all of the currently ready to be dispatched SRs hidden.
Starting State: 
image
After Toggling:
image


UI/UX Request: Can we move the `+` symbol on the Dispatch Map for adding new team members to justify right at the end of the quick search?

**Review by trevorskaggs — APPROVED** [review]

**Pull request merged**
