### PR TITLE
696 bugs and features

### PR DESCRIPTION
**Pull request by AlexMountain**

### CODE REVIEW

**Comment by parksjr** [comment]
Closes #611

**Comment by parksjr** [comment]
Closes #615

**Review by trevorskaggs — COMMENTED** [review]
- [x] https://github.com/trevorskaggs/shelterly/issues/619
- [x] https://github.com/trevorskaggs/shelterly/issues/615
- [x] https://github.com/trevorskaggs/shelterly/issues/611
- [x] https://github.com/trevorskaggs/shelterly/issues/580
- 2 Minor Change Requests: 
image
- Can we add a Label back for the Current Visit Notes Field (next to all the blank lines)
- Can we add a Header for the Previous Visit Notes Section? If we do that we can probably then just do `Date`: `Note`

**Review by trevorskaggs — APPROVED** [review]
Thanks for the fixes! :shipit:

**Pull request merged**
