### PR TITLE
Handle duplicate owners

### PR DESCRIPTION
**Pull request by AlexMountain**
- [x] Handle duplicate owners when adding from the SR, Owner/Reporter, or Animal pages.
- [x] Handle duplicate owners when adding through the Intake stepper workflow.
- [x] Handle duplicate reporters when adding through Intake workflow by using existing Person if available.

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs Ready for review!

**Comment by trevorskaggs** [comment]
Looking pretty good so far!

1. Was able to run into a little discrepancy on phone number check:
 
Original Owner:
image

When entering a new Hotline, with the phone number of `5315151214` I get the expected popup:
image

If I instead enter with dashes or parens (I found this the first time because I copy/pasted from the Owner Details page), then I dont get the popup:
image

I know we are doing some cool post formatting to that field as phone numbers are wonky AF. Wonder if we need to do that validation logic to the field before doing the dupe check?

2. Seems like we are checking for reporters also during Owner check?
Reporter Details: 
image
Dupe Check
image

Also fun fact: for a reporter the `Click here to view the owner` link will actually open a valid page as its just a person object and make it look like they are the owner!

image

**Comment by AlexMountain** [comment]
@trevorskaggs 

1.  Good catch. I'll play around with it.
2. Yes that was intentional. Reporter objects are still person objects in our system and it made more sense to reuse the person if the information is identical.  It would technically make them an owner and reporter (but for different animals).  Are there any issues with this?

**Comment by trevorskaggs** [comment]
2. Nah, I think the only problem I see is in that we say "Owned Animals" on the Reporter Details page.

**Comment by AlexMountain** [comment]
@trevorskaggs Should be fixed.

**Review by trevorskaggs — APPROVED** [review]
Heck yea! :shipit:

**Pull request merged**
