### PR TITLE
Reactify animals

### PR DESCRIPTION
**Pull request by rmeyers4**

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs I'm not seeing the "Add another" button when editing an animal?  Can you confirm on your end?

Added dynamic placeholder text, good idea!

**Comment by trevorskaggs** [comment]
You are right! That issue disappeared after I repulled the newest changes.  Playing back through it again I did run into another issue though!
image
When I go through the Hotline - Owner Calling workflow, it seems to bonk when attempting to save the SR at the very end!

**Comment by AlexMountain** [comment]
Good catch, fixed!

**Comment by trevorskaggs** [comment]
Muy bueno! :shipit:

**Pull request merged**
