### PR TITLE
User Action History

### PR DESCRIPTION
**Pull request by AlexMountain**
Track user actions for:
- [x] Animals (created, updated)
- [x] Service Requests (created, updated, assigned, opened, closed)
- [x] People (created, updated)
- [x] Shelter, Building, and Rooms (created, updated, animal added, animal removed)
- [x] Evac (created, closed)

- [x] Add expandable History section under the details of each object respectfully.

### CODE REVIEW

**Comment by AlexMountain** [comment]
@trevorskaggs Ready for review!

**Comment by trevorskaggs** [comment]
Looks like I am missing the migrations for this bad boy!

**Comment by AlexMountain** [comment]
Sorry, it's there's in the requirements and settings.  You need to install `django-activity-stream` and just run `migrate`.

**Review by trevorskaggs — APPROVED** [review]
Looking awesome, lets send this bad boy! :shipit:

**Pull request merged**
