### PR TITLE
adds the animal care schedule as a downloadable ShelterlyPDF™

### LINKED ISSUE #455: Convert Animal Care Schedule to PDF
Currently the Animal Care Schedule is a hacked together django url with a template rendering.  Lets convert this to our new PDF approach.  The current structure/fields are roughly correct.
[AnimalCareSchedule.pdf](https://github.com/trevorskaggs/shelterly/files/9122974/AnimalCareSchedule.pdf)

Nice to Haves:
- [ ] QR Code in upper right corner to Animal Details page

### PR DESCRIPTION
**Pull request by parksjr**
closes #455

### CODE REVIEW

**Comment by trevorskaggs** [comment]
Spun this guy up and it seems to have an issue!

image
Tried both with an animal that does and does not have a picture!

**Comment by trevorskaggs** [comment]
Also, just noticed are you able to add page numbers to Owner Summary report in this ticket @parksjr ?

**Comment by trevorskaggs** [comment]
One more item: looks like the Animal Status header is duplicating on the DAR printout!
image

**Comment by parksjr** [comment]
Closing this PR as I have a new one that includes issues #455 and #456

**Pull request closed without merging**
