### PR TITLE
search page upgrades #540

### LINKED ISSUE #540: Search Pages Upgrades
- Fix spaces between buttons on all Search Pages
- Add Date Range Search for SR Search
- Add Download as Geojson for SR Search

### PR DESCRIPTION
**Pull request by parksjr**
- uniform spacing on buttons
- filter by date on SR search

### For QA

- View all search pages, spacing between all buttons to the right of the search input should be uniform
- View Service Request search page, filter results by single date or date range.
- View Dispatch search page, ensure filter by date works with no regressions.

closes #540

### CODE REVIEW

**Comment by trevorskaggs** [comment]
Found a few issues while testing this, not sure they came from your new behavior, but are related to the date selector:
1. If you set the date range, then clear (by clicking in the box and deleting all the text) the search seems to no longer work.
2. If you search for a date range, which yields no results, the "Closed" SR search has 2 page buttons:
image
3. Same behavior as #2above, but also happens on the "Resolved" DA search: 
image

For the ones above, if you filter to no results using the search box you dont get any buttons:
image
image

**Comment by parksjr** [comment]
Pushed up fixes for the issues found. Also added a handy little clear button in the date range picker to avoid manually selecting all, deleting, then pressing enter to clear the date range filter.

**Comment by parksjr** [comment]
I made the useDateRange hook a little better and fixed tests that I broke last night

**Comment by trevorskaggs** [comment]
Nice work @parksjr .  One small change, then lets merge this bad boy.

Can we move the `x` up slightly to line up with the dates?
image

**Comment by parksjr** [comment]
Fixed, and merging!

**Pull request merged**
