### PR TITLE
Dispatch Workflow - SR Selection

### PR DESCRIPTION
**Pull request by AlexMountain**
See linked issue for details

### CODE REVIEW

**Comment by trevorskaggs** [comment]
Confirmed: Animal Form issue resolved.!

**Comment by trevorskaggs** [comment]
Playing with this a bit more and very pumped! Is it fairly simple right now to provide an ongoing tally of total animal counts?  I'm thinking that might be useful to have right under the map in some capacity.

**Comment by trevorskaggs** [comment]
Looking good, DEMO IS GOING TO BE AWESOME!

**Comment by AlexMountain** [comment]
@rmeyers4 Ready for a code review!

**Review by rmeyers4 — APPROVED** [review]
This is great! I wasn't able to break it, and the functionality is snazzy. I made two minor changes - moved the querystring params from the axios call to a `params` argument, and replaced the BS container divs with `react-bootstrap` classes. If you're good with that merge away 🪑

**Pull request merged**
